version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s. %(name)s - %(message)s"
    datefmt: "%d/%m/%Y %I:%M:%S %p"
    
  detailed:
    format: "[%(asctime)s] %(levelname)s. %(name)s - %(filename)s:%(lineno)d - %(message)s"
    datefmt: "%d/%m/%Y %I:%M:%S.%f %p"
  
  short:
    format: "%(levelname)s. %(filename)s - %(message)s"
    datefmt: "%I:%M:%S %p"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: short
    filename: ./output/logs/verbosa.log
    mode: a
    encoding: utf-8
  
  daily_rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: short
    filename: ./output/logs/verbosa_daily.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8
  
  testing_rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./output/logs/verbosa_testing.log
    when: S
    interval: 1
    backupCount: 5
    encoding: utf-8

loggers:
  verbosa:
    level: DEBUG
    handlers:
      - console
      - testing_rotating_file
    propagate: False